# Generated by Django 5.0.7 on 2024-08-03 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0003_alter_blog_status"),
    ]

    operations = [
        migrations.RenameField(
            model_name="blog",
            old_name="is_feature",
            new_name="is_featured",
        ),
    ]
